### ISSUE TITLE
always crash when run large number of transactions

### ISSUE THREAD

**Issue by bwang221** [bvinc/go-sqlite-lite#24]
commits >100k records in transaction. always run into this at some point

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40abad1]

goroutine 35 [running]:
github.com/bvinc/go-sqlite-lite/sqlite3.(*Conn).exec.func1(0x0, 0xc0029680a0, 0x0)
	/Users/bwang/work/gobrindexer/src/github.com/bvinc/go-sqlite-lite/sqlite3/sqlite3.go:670 +0x31
github.com/bvinc/go-sqlite-lite/sqlite3.(*Conn).exec(0x0, 0xc0029680a0, 0x0, 0x0)
	/Users/bwang/work/gobrindexer/src/github.com/bvinc/go-sqlite-lite/sqlite3/sqlite3.go:670 +0x41
github.com/bvinc/go-sqlite-lite/sqlite3.(*Conn).Exec(0x0, 0xc0029680a0, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bwang/work/gobrindexer/src/github.com/bvinc/go-sqlite-lite/sqlite3/sqlite3.go:416 +0xd5
cray.com/brindexer/db.SqliteWrapper.Database(0xc0000a46c0, 0x25, 0x0, 0xc000097890, 0xc00009a3a8, 0x44802, 0x0)

**Comment by bwang221** [comment]
resolved
